"""empty message

Revision ID: 336383a51693
Revises: c5857e6b9afe
Create Date: 2023-08-23 16:36:11.607074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336383a51693'
down_revision = 'c5857e6b9afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['country'])
        batch_op.create_unique_constraint(None, ['city'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('city')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
