"""empty message

Revision ID: 869bf653034c
Revises: 1519f934a4fb
Create Date: 2023-08-24 01:43:12.672418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869bf653034c'
down_revision = '1519f934a4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('cellphone',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('cellphone',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
