"""empty message

Revision ID: 88382ce8ddf9
Revises: a87b697880f8
Create Date: 2023-08-22 23:45:51.735977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88382ce8ddf9'
down_revision = 'a87b697880f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
