"""empty message

Revision ID: ede4fabe27b4
Revises: d4a0b5cda363
Create Date: 2023-08-31 01:55:40.179694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede4fabe27b4'
down_revision = 'd4a0b5cda363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='seller_product_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='seller_product_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='seller_product_pkey')
    )
    # ### end Alembic commands ###
