"""empty message

Revision ID: f32b9af1c59b
Revises: 020adaf3c605
Create Date: 2023-09-06 02:06:54.820939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32b9af1c59b'
down_revision = '020adaf3c605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_state', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('exchange_state')

    # ### end Alembic commands ###
